### ISSUE TITLE
License Discussion for Milestone 4 Requirement

### ISSUE THREAD

**Issue by sweber15** [UBC-MDS/edar#68]
- [ ] Examine the license for your project.
- [ ] Discuss and reason the license choice by opening issues in both Python and R repositories.
- [ ] Include a link of these issues in your final_project repository's README.md file.

**Comment by sweber15** [comment]
Issue has been re-created #69
